version: '3.5'

services:

  web:
    image: nginx:stable
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../../nginx/sites-enable:/etc/nginx/sites-enable
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ndb_net
  
  monitoring:
    restart: always
    container_name: monitoring
    build: .
    command: pipenv run python email_project/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./email_project/db.sqlite3:/usr/src/app/email_project/db.sqlite3
    networks:
      - ndb_net

networks:
  ndb_net:
    external:
      name: ndb_net